sudo:
    - required
language: 
    - node_js
node_js:
    - 7
before_install:
    - "curl https://install.meteor.com | /bin/sh"
services:
    - mongodb
install:
    - npm install phantomjs-prebuilt -g
    - npm install -g mocha-phantomjs
    - npm install -g gulp
    - npm install -g bower
    - npm install
before_script:
    - phantomjs -v
    - mocha-phantomjs -V
    - gulp &
    - sleep 5
script:
    - cd soen341webapp
    - pwd
    - make start
    - make test
group:
    - stable
dist:
    - trusty
os:
    - linux
