sudo: required
language: node_js
node_js: "7"
before_install:
    - "curl https://install.meteor.com | /bin/sh"
services: mongodb
install:
    - npm install -g phantomjs-prebuilt
    - npm install -g mocha
    - npm install -g mocha-phantomjs
    - npm install -g gulp
    - npm install -g bower
    - npm install
before_script:
    - phantomjs -v
    - mocha-phantomjs -V
    - gulp &
    - sleep 5
script:
    - cd soen341webapp #cd to the project folder
    - pwd #make sure we are in the good directory
    - make basic-test #run basic test
group: stable
dist: trusty
os: linux
